
name: Build

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
    - name: Build 
      run: |
        npm ci
        npm run build
