name: "Containerize"

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build container and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: halo-collectibles:latest
